version: "2"

services:
  tomcat:
    image: softwarelabsit/softwarelabsit-bank
    depends_on: ["bankdb"]
    ports: ["4801:8080", "4809:8000"]
    volumes: ["./docker/log:/var/log/tomcat"]

  bankdb:
    image: postgres:9.6
    volumes: ["./docker/trackingdb:/var/lib/postgresql/data"]
    ports: ["4802:5432"]
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
      POSTGRES_DB: bank
